name: 'Sync secrets to AWS'
author: 'Dennis Beatty'
description: 'Sends specified values to AWS Secrets Manager'
branding:
  icon: 'upload-cloud'
  color: 'orange'

inputs:
  secret-arn:
    description: 'The ARN of the Secrets Manager secret that should be updated'
    required: true
  secret-values:
    description: 'The values to add to the secret. These should be written in KEY=value format with each value on its own line'
    required: true

runs:
  using: 'node20'
  main: 'dist/index.js'
